#!/usr/bin/env python3

import sys
import numpy
import time
from math import factorial, exp, sqrt, pi


def simpsonCalcul(u, s, i):
	return (1 / (float(s) * sqrt(2 * pi))) * exp(-((float(i) - float(u))**2) / (2 * float(s)**2))


def calcul_pourct(u, s):
	tab = []
	for i in range (0, 201):
		tab.append(float(simpsonCalcul(u, s, i)))
	return tab

def printTab(tab):
	for i in range (0, len(tab)):
		print("{0:} {1:.5f}".format(i ,tab[i]))

#def getPrct(tab, start, end):
#	res = 0
#	for i in range(start, end):
#		res += float(tab[i])
#	return float(res) * 100

def getPrct(start, end, u, s):
	res = 0
	i = start
	while (i < end):
		res += simpsonCalcul(u, s, i)
		i += 0.01
	return float(res)

def Try_Int(s):
    try:
        int(s)
        return True
    except ValueError:
        return False

        
if len(sys.argv) == 2 and sys.argv[1] == "-h":
	print("USAGE")
	print("\t./205IQ u s [IQ1] [IQ2]\n")
	print("DESCRIPTION")
	print("\tu\tmean")
	print("\ts\tstandard deviation")
	print("\tIQ1\tminimum IQ")
	print("\tIQ2\tmaximum IQ")
	exit(0)

if len(sys.argv) < 3:
    exit(84)

if (Try_Int(sys.argv[1]) == False or Try_Int(sys.argv[2]) == False):
	print("Mean and Standard deviation must be int")
	exit(84)

u = int(sys.argv[1])
s = int(sys.argv[2])

if (u < 0 or u > 200 or s <= 0 or s > 200):
	print("Mean and Standard deviation can't be negatif")
	exit(84)

prct_tab = calcul_pourct(u,s)
if (len(sys.argv) == 3):
	printTab(prct_tab)
elif (len(sys.argv) == 4):
	if (Try_Int(sys.argv[3]) == False or int(sys.argv[3]) < 0):
		print("Minimum IQ must be an positive int")
		exit(84)
	#val = getPrct(prct_tab, 0, int(sys.argv[3]))
	val = getPrct(0, int(sys.argv[3]), u, s)
	minus = int(sys.argv[3])
	print("{:.1f}% of people have an IQ inferior to {}".format(val, minus))
elif(len(sys.argv) == 5):
	if (Try_Int(sys.argv[3]) == False or Try_Int(sys.argv[4]) == False or int(sys.argv[3]) < 0 or int(sys.argv[4]) < 0):
		print("Minimum and maximum IQ must be an positive int")
		exit(84)
	#val = getPrct(prct_tab, int(sys.argv[3]), int(sys.argv[4]))
	val = getPrct(int(sys.argv[3]), int(sys.argv[4]), u, s)
	minus = int(sys.argv[3])
	maxus = int(sys.argv[4])
	print("{:.1f}% of people have an IQ between {} and {}".format(val, minus, maxus))
else:
	print("Too much arguments")
	exit(84)
