##
## EPITECH PROJECT, 2018
## Torus
## File description:
## Bilel Bouricha
##

NAME	=	203hotline

SRC	=	src/203hotline

all:
	cat $(SRC) > $(NAME)
	chmod 711 $(NAME)

fclean:
	rm -f $(NAME)

re: fclean all
